# Select a specfic if possible, otherwise use a minimal image that gets you close
FROM node:14.8.0-alpine3.10

# Expose port
EXPOSE 3000

# Start
WORKDIR /home/app/frontend
ENTRYPOINT [ "npm", "run", "start" ]
