# Select a specfic if possible, otherwise use a minimal image that gets you close
FROM node:14.8.0-alpine3.10

# Expose port
EXPOSE 8080

# Start
WORKDIR /home/app/backend
ENTRYPOINT [ "npm", "run", "start" ]
