# [Choice] Node.js version: 14, 12, 10
ARG VARIANT=16
FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:${VARIANT}

# Copy the full repository into the /workspace directory
WORKDIR /workspace
COPY . .
